spring:
  application:
    name: auth
  datasource:
    url: jdbc:h2:mem:authdb
    username: user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /api

app:
  security:
    access-token:
      secret-key: "fEo++duKwfrb7kUw8i+6YSqm7CHHE5RxFtUASvCY+/I="